version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  api:
    build:
      dockerfile: Dockerfile
    environment:
      FRONTEND_HOST: ${FRONTEND_HOST}
      SESSION_SECRET: ${SESSION_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      COGNITO_DOMAIN: ${COGNITO_DOMAIN}
      COGNITO_CALLBACK_URL: ${COGNITO_CALLBACK_URL}
      COGNITO_OPENID_DISCOVERY_URL: ${COGNITO_OPENID_DISCOVERY_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080


